#!/bin/sh

# fzf
# https://github.com/junegunn/fzf

# Dependencies:
# – fd (https://github.com/sharkdp/fd)
# – bat (https://github.com/sharkdp/bat)

fd --type file . "$@" |
fzf --preview "bat --style=numbers --color=always --line-range :$FZF_PREVIEW_LINES {}" |
:edit
